import type { CollectionConfig } from 'payload'
import { rebuildAfterChange, rebuildAfterDelete } from '../hooks/globalRebuildHook'

const Galleries: CollectionConfig = {
  slug: 'galleries',
  admin: {
    useAsTitle: 'title',
  },
  access: {
    read: () => true, // Ensure public readability
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'slug', // Good for generating clean URLs if needed (e.g., /galleries/roofing-projects)
      type: 'text',
      unique: true,
      admin: {
        readOnly: true, // Usually autogenerated or manually set once
      },
      hooks: {
        beforeValidate: [
          ({ value, data }) => {
            if (!value && data?.title) {
              return data.title
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^\w-]+/g, '')
            }
            return value
          },
        ],
      },
    },
    {
      name: 'images',
      type: 'array',
      label: 'Gallery Images',
      minRows: 1, // Ensure at least one image is uploaded
      labels: {
        singular: 'Image',
        plural: 'Images',
      },
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media', // This assumes you have a 'media' collection for uploads
          required: true,
        },
        {
          name: 'caption',
          type: 'text',
          localized: true,
        },
      ],
    },
  ],
}

export default Galleries
